### ISSUE TITLE
Cannot build benchmark

### ISSUE THREAD

**Issue by remysucre** [bos/aeson#310]
Please document how to build the benchmark suit. I've tried cabal build, make, cabal bench but nothing worked.

**Comment by epsilonhalbe** [comment]
it is quite simple
you see there is a directory `benchmarks`

```
> git clone https://github.com/bos/aeson
> cd aeson
> cabal sandbox init
> cabal build -j --dep
[...] wait/fetch coffee/sing a song
> cabal install ./benchmarks
[...] wait/have an interesting conversation with somebody
> ./.cabal-sandbox/bin/aeson-benchmark-micro
see the outputs of your benchmarks
```

I hope this solves your problem

**Comment by remysucre** [comment]
Are you sure it builds? I'm still getting 

```../Data/Aeson/TH.hs:5:0:
     fatal error: overlapping-compat.h: No such file or directory
     #include "overlapping-compat.h"
```

Also the `--dep` flag isn't recognized.

**Comment by epsilonhalbe** [comment]
I tried the aeson-0.10.0.0 from hackage - (had to copy some files from gh for the tests to work) but other than that the build worked.

with the gh master I have tried a stack init => stack build, here I had to add the path to the include directory in the `stack.yaml` file.

```
aeson-gh > stack --version
Version 0.1.5.0, Git revision a30f022c3dca7c489e08f31908ea77c3bf305375 (2159 commits) X86_64
```

I think this would also work with the newer stack 1.6

```
aeson-gh >  cat stack.yaml
# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: nightly-2015-10-30

# Local packages, usually specified by relative directory name
packages:
- '.'
- examples/
- benchmarks/

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags:
  aeson-benchmarks:
    old-locale: false
  aeson:
    old-locale: false
    developer: false

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
extra-include-dirs: [/absolute/path/to/aeson/include]
# extra-lib-dirs: [/path/to/dir]
```

Please try to build it with stack and tell me wether it works for you.
